
x-volumes: &volumes
  - ${MAGEFLEET_SSL_DIR}/rootca/certs:/etc/ssl/magefleet-rootca-cert:ro
  - ${MAGEFLEET_COMPOSER_DIR}:/home/www-data/.composer:cached
  - .${MAGEFLEET_WEB_ROOT:-}/:/var/www/html:cached
  - bashhistory:/bash_history
  - sshdirectory:/home/www-data/.ssh

x-extra_hosts: &extra_hosts
    - ${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}

services:
  nginx:
    depends_on:
      - php-fpm

  php-fpm:
    hostname: "${MAGEFLEET_ENV_NAME}-php-fpm"
    image: ${MAGEFLEET_IMAGE_REPOSITORY}/php-fpm${MAGEFLEET_SVC_PHP_IMAGE_SUFFIX:-}:${PHP_VERSION:-7.4}${MAGEFLEET_SVC_PHP_VARIANT:-}
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_PATH_ENV:-/tmp/ssh-auth.sock}
      - NODE_VERSION=${NODE_VERSION:-12}
      - COMPOSER_VERSION=${COMPOSER_VERSION:-1}
      - COMPOSER_MEMORY_LIMIT=-1
      - HISTFILE=/bash_history/.bash_history
      - CHOWN_DIR_LIST=${CHOWN_DIR_LIST:-}
    volumes: *volumes
    extra_hosts: *extra_hosts

  php-debug:
    hostname: "${MAGEFLEET_ENV_NAME}-php-debug"
    image: ${MAGEFLEET_IMAGE_REPOSITORY}/php-fpm${MAGEFLEET_SVC_PHP_IMAGE_SUFFIX:-}:${PHP_VERSION:-7.4}${MAGEFLEET_SVC_PHP_VARIANT:-}-${XDEBUG_VERSION:-debug}
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_PATH_ENV:-/tmp/ssh-auth.sock}
      - NODE_VERSION=${NODE_VERSION:-12}
      - COMPOSER_VERSION=${COMPOSER_VERSION:-1}
      - COMPOSER_MEMORY_LIMIT=-1
      - PHP_IDE_CONFIG=serverName=${MAGEFLEET_ENV_NAME}-docker
      - HISTFILE=/bash_history/.bash_history
      - CHOWN_DIR_LIST=${CHOWN_DIR_LIST:-}
    volumes: *volumes
    extra_hosts: *extra_hosts
    depends_on:
      - php-fpm
volumes:
  bashhistory:
  sshdirectory:
