services:
  rabbitmq:
    hostname: "${MAGEFLEET_ENV_NAME}-rabbitmq"
    image: ${MAGEFLEET_IMAGE_REPOSITORY}/rabbitmq:${RABBITMQ_VERSION:-3.8}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${MAGEFLEET_ENV_NAME}-rabbitmq.tls=true
      - traefik.http.routers.${MAGEFLEET_ENV_NAME}-rabbitmq.rule=Host(`rabbitmq.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${MAGEFLEET_ENV_NAME}-rabbitmq.loadbalancer.server.port=15672
      - traefik.docker.network=${MAGEFLEET_ENV_NAME}_default
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
